site_name: Joomla Study Zone
theme:
  name: material
nav:
  - 首頁: index.md
  - 關於我: https://github.com/petertseng0517
  - 基礎joomla教學:
      - 取得Joomla管理帳號: joomla/取得Joomla管理帳號.md
      - 登入Joomla系統: joomla/登入Joomla系統.md
      - 編輯Joomla文章: joomla/編輯Joomla文章.md
      - 在joomla文章新增圖片: joomla/在joomla文章新增圖片.md
      - 在joomla文章內文放置超連結: joomla/在joomla文章內文放置超連結.md
      - 在joomla文章內文放置檔案下載連結: joomla/在joomla文章內文放置檔案下載連結.md
      - Joomla編輯者切勿有以下行為: joomla/Joomla編輯者切勿有以下行為.md
  - 進階教學(醫務部): 
      - 編輯醫療科首頁: joomla/編輯醫療科首頁.md
      - 編輯醫師資料: joomla/編輯醫師資料.md
      - 新增醫療科的衛教內容: joomla/新增醫療科的衛教內容.md
      - 新增醫療科的最新消息: joomla/新增醫療科的最新消息.md
  - 進階教學(醫事室):
      - 更新門診表: joomla/更新門診表.md
      - 疫苗公告(流感、M痘): joomla/疫苗公告(流感、M痘).md
  - 進階教學(總務室):
      - 上架招標公告: joomla/上架招標公告.md
      - 編輯樓層介紹: joomla/編輯樓層介紹.md